# Generated by Django 3.2.1 on 2021-05-09 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='preorder',
            options={'verbose_name': 'Предзаказ', 'verbose_name_plural': 'Предзаказы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='register_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='master',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(upload_to='masters_photo/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='master',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='master',
            name='work_times',
            field=models.ManyToManyField(to='crm.TimeTable', verbose_name='Рабочие периоды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='finish_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время завершения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.master', verbose_name='ID Мастера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(to='crm.Service', verbose_name='Список услуг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.master', verbose_name='ID Мастера'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='reserved_time',
            field=models.DateTimeField(verbose_name='Дата брони'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(upload_to='services_photo/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.DateTimeField(verbose_name='Время'),
        ),
    ]
