# Generated by Django 3.2.1 on 2021-05-09 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210510_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.master', verbose_name='Мастер'),
        ),
    ]
