# Generated by Django 3.2.1 on 2021-05-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_customer_register_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
            ],
        ),
        migrations.RemoveField(
            model_name='master',
            name='work_times',
        ),
        migrations.AddField(
            model_name='timetable',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.master'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.date'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.time'),
        ),
    ]
