# Generated by Django 3.2.1 on 2021-05-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20210511_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(null=True, verbose_name='Короткое описание'),
        ),
    ]
