# Generated by Django 3.2.2 on 2021-05-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_master_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'verbose_name': 'Дата', 'verbose_name_plural': 'Даты'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'Время', 'verbose_name_plural': 'Время'},
        ),
    ]
