# Generated by Django 3.2.2 on 2021-05-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20210515_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
