# Generated by Django 3.2.2 on 2021-05-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_timetable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
