# Generated by Django 3.2.2 on 2021-05-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
