# Generated by Django 3.2.2 on 2021-05-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('crm', '0021_customuser_customuserzz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='date',
        ),
        migrations.AddField(
            model_name='timetable',
            name='date',
            field=models.ManyToManyField(to='crm.Date', verbose_name='Дата'),
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='master',
        ),
        migrations.AddField(
            model_name='timetable',
            name='master',
            field=models.ManyToManyField(to='crm.Master', verbose_name='Master'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='time',
            field=models.ManyToManyField(to='crm.Time', verbose_name='Время'),
        ),
        migrations.DeleteModel(
            name='CustomUserZz',
        ),
    ]
