# Generated by Django 3.2.2 on 2021-05-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20210520_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='date',
        ),
        migrations.AddField(
            model_name='timetable',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.date', verbose_name='Дата'),
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='master',
        ),
        migrations.AddField(
            model_name='timetable',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.master', verbose_name='Master'),
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.time', verbose_name='Время'),
        ),
    ]
