# Generated by Django 3.2.2 on 2021-05-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20210520_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='master',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
