# Generated by Django 3.1 on 2021-06-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20210606_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorder',
            old_name='master_id',
            new_name='master',
        ),
        migrations.AddField(
            model_name='preorder',
            name='reserved_date',
            field=models.DateField(null=True, verbose_name='Дата брони'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='reserved_time',
            field=models.TimeField(null=True, verbose_name='Время брони'),
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
