# Generated by Django 3.1 on 2021-06-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_auto_20210607_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='master',
            field=models.TextField(verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='reserved_date',
            field=models.TextField(null=True, verbose_name='Дата брони'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='reserved_time',
            field=models.TextField(null=True, verbose_name='Время брони'),
        ),
    ]
