# Generated by Django 3.1 on 2021-06-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_auto_20210607_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='reserved_time',
            field=models.TimeField(null=True, verbose_name='Время брони'),
        ),
    ]
