# Generated by Django 3.1 on 2021-06-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_auto_20210607_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена услуги'),
        ),
    ]
