# Generated by Django 3.1 on 2021-06-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(null=True, verbose_name='Общая стоимость'),
        ),
    ]
