# Generated by Django 3.1 on 2021-06-08 06:42

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_auto_20210608_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(to='crm.Service', verbose_name='Список услуг'),
        ),
    ]
