# Generated by Django 3.1 on 2021-06-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_auto_20210608_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(to='crm.Service', verbose_name='Список услуг'),
        ),
    ]
